name: smart_reply_app
description: "AI-powered messaging assistant for crafting smart replies and enhancing messages."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  

  http: ^1.2.0
  
  # State management
  provider: ^6.1.2
  
  # Local storage for settings
  shared_preferences: ^2.3.4

  url_launcher: ^6.3.0
  
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/